// =============================================================================
// shopkeeper_app/main.dart — entrypoint for Sunil-bhaiya's ops app.
//
// Same bootstrap sequence as customer_app/main.dart, except:
//   - shopId is resolved from the Google operator's custom claim after
//     sign-in, NOT hardcoded at compile time. Until S4.1 lands (Sprint 3),
//     we use the flagship shopId as the default.
//   - Auth flow is Google Sign-In (AuthTier.googleOperator), NOT anonymous.
// =============================================================================

import 'dart:async';

import 'package:firebase_auth/firebase_auth.dart' as fb;
import 'package:firebase_remote_config/firebase_remote_config.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lib_core/lib_core.dart';
import 'package:logging/logging.dart';

import 'app.dart';
// Generated by `flutterfire configure`. Commit to git — points to dev
// by default. Staging/prod bundles override at build time.
import 'firebase_options.dart';

Future<void> main() async {
  _configureLogging();

  await runZonedGuarded<Future<void>>(
    () async {
      WidgetsFlutterBinding.ensureInitialized();
      await FirebaseClient.initialize(
        options: DefaultFirebaseOptions.currentPlatform,
      );

      final remoteConfig = await RemoteConfigLoader.initialize();

      final authProvider = AuthProviderFactory.build(
        remoteConfig: remoteConfig,
        firebaseAuth: fb.FirebaseAuth.instance,
      );

      await Observability.initialize();

      // PRD I6.3 — verify persisted session (same rationale as customer_app).
      // For ops users this means the bhaiya / son / munshi doesn't re-type
      // Google Sign-In every morning.
      await SessionBootstrap.verifyPersistedUser(
        authProvider: authProvider,
        analytics: Observability.analytics,
        crashlytics: Observability.crashlytics,
      );

      runApp(
        ProviderScope(
          overrides: [
            // Sprint 1 default. After S4.1 Google Sign-In lands (Sprint 3),
            // the real shopId comes from the operator's custom claim.
            shopIdProviderProvider.overrideWithValue(
              const ShopIdProvider(ShopIdProvider.flagshipShopId),
            ),
            shopkeeperAuthProviderInstance.overrideWithValue(authProvider),
          ],
          child: const ShopkeeperApp(),
        ),
      );
    },
    (error, stack) {
      Observability.crashlytics.recordError(error, stack, fatal: true);
    },
  );
}

void _configureLogging() {
  Logger.root.level = kDebugMode ? Level.ALL : Level.INFO;
  Logger.root.onRecord.listen((record) {
    if (kDebugMode) {
      debugPrint(
          '[${record.level.name}] ${record.loggerName}: ${record.message}');
    } else {
      Observability.crashlytics.log('${record.loggerName}: ${record.message}');
    }
  });
}

/// Provider override hook — main() overrides this with the concrete
/// AuthProvider resolved from Remote Config.
final shopkeeperAuthProviderInstance = Provider<AuthProvider>((ref) {
  throw UnimplementedError(
    'shopkeeperAuthProviderInstance must be overridden in main.dart',
  );
});

/// Singleton MediaStore for the shopkeeper app. Used by voice note recording,
/// golden hour photo capture, and greeting management screens. Avoids ad-hoc
/// MediaStoreCloudinaryFirebase construction per handoff §4 gotcha.
final mediaStoreProvider = Provider<MediaStore>((ref) {
  final cloudName =
      FirebaseRemoteConfig.instance.getString(FeatureFlags.cloudinaryCloudName);
  return MediaStoreCloudinaryFirebase(
    firebaseStorage: FirebaseStorage.instance,
    cloudinaryCloudName: cloudName.isNotEmpty ? cloudName : 'yugma-dukaan-dev',
  );
});
