// =============================================================================
// customer_app/main.dart — entrypoint for the customer app.
//
// Bootstrap sequence (order is load-bearing — do not reorder):
//   1. Flutter bindings
//   2. Firebase + App Check                           (FirebaseClient.initialize)
//   3. Remote Config (fetch + activate with defaults) (RemoteConfigLoader)
//   4. AuthProvider resolved from Remote Config flag  (AuthProviderFactory)
//   5. ShopId resolved from deep link / prefs / fallback (TenantResolver)
//   6. Observability (Crashlytics + Analytics + Performance, runZonedGuarded)
//   7. runApp inside the same runZonedGuarded block
//   7.5 Start re-bind stream listener (WS1.5)
//
// See SAD §4 Flow 1 (first-time customer) for the user-facing behavior this
// bootstrap enables.
// =============================================================================

import 'dart:async';

import 'package:firebase_auth/firebase_auth.dart' as fb;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lib_core/lib_core.dart';
import 'package:logging/logging.dart';

import 'app.dart';
// Generated by `flutterfire configure`. Commit to git — it points to the
// dev Firebase project by default. Staging/prod bundles override at build time.
import 'firebase_options.dart';

final _log = Logger('main');

Future<void> main() async {
  // Configure logging before anything else so bootstrap errors are visible.
  _configureLogging();

  // Everything runs inside runZonedGuarded so bindings + runApp share the
  // same zone (Flutter requirement since 3.24). Any async errors are caught
  // by Observability's PlatformDispatcher hook.
  await runZonedGuarded<Future<void>>(
    () async {
      // Step 1 — Flutter bindings (MUST be in same zone as runApp)
      WidgetsFlutterBinding.ensureInitialized();
      // Step 2 — Firebase + App Check
      await FirebaseClient.initialize(
        options: DefaultFirebaseOptions.currentPlatform,
      );

      // Step 3 — Remote Config
      final remoteConfig = await RemoteConfigLoader.initialize();

      // Step 4 — AuthProvider resolution
      final authProvider = AuthProviderFactory.build(
        remoteConfig: remoteConfig,
        firebaseAuth: fb.FirebaseAuth.instance,
      );

      // Step 5 — ShopId resolution (WS1): deep link → prefs → flagship fallback
      final shopId = await TenantResolver.resolveShopId();
      _log.info('Resolved shopId=$shopId');

      // Step 6 — Observability
      await Observability.initialize();

      // Step 6.5 — PRD I6.3: verify persisted session from refresh token.
      await SessionBootstrap.verifyPersistedUser(
        authProvider: authProvider,
        analytics: Observability.analytics,
        crashlytics: Observability.crashlytics,
      );

      // Step 7 — Run the app inside a ProviderScope with the resolved
      // shopId + authProvider overridden.
      runApp(
        ProviderScope(
          overrides: [
            shopIdProviderProvider.overrideWithValue(
              ShopIdProvider(shopId),
            ),
            authProviderInstanceProvider.overrideWithValue(authProvider),
          ],
          child: const CustomerApp(),
        ),
      );

      // Step 7.5 — WS1.5: listen for deep-link re-bind while app is running.
      // Dialog is deferred to a follow-up story; for now log + persist only.
      TenantResolver.uriLinkStream.listen((uri) {
        final newShopId = TenantResolver.parseTenantSlug(uri);
        if (newShopId != null && newShopId != shopId) {
          _log.info('shop re-bind requested: $newShopId (current=$shopId)');
          unawaited(TenantResolver.persistShopId(newShopId));
        }
      });
    },
    (error, stack) {
      Observability.crashlytics.recordError(error, stack, fatal: true);
    },
  );
}

void _configureLogging() {
  Logger.root.level = kDebugMode ? Level.ALL : Level.INFO;
  Logger.root.onRecord.listen((record) {
    // Pretty-print in debug; JSON-ish in release for Crashlytics log capture.
    if (kDebugMode) {
      debugPrint(
          '[${record.level.name}] ${record.loggerName}: ${record.message}');
    } else {
      Observability.crashlytics.log('${record.loggerName}: ${record.message}');
    }
  });
}

/// Provider override hook — main() overrides this with the concrete
/// AuthProvider resolved from Remote Config. Feature code consumes it via
/// `ref.watch(authProviderInstanceProvider)`.
final authProviderInstanceProvider = Provider<AuthProvider>((ref) {
  throw UnimplementedError(
    'authProviderInstanceProvider must be overridden in main.dart',
  );
});
